ReportsWebApp/Models/PlanActualReport.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ReportsWebApp.Models
{
    public class PlanReportModel
    {
        public List<string> DepartureCities { get; set; }

        public List<string> ArrivalCities { get; set; }

        public List<PlanActualReport> report { get; set; }
    }

    public class PlanActualReport
    {
        [Display(AutoGenerateField = false)]
        public int PlanId { get; set; }

        [Display(Name = "Departure city")]
        public string DepartureCity { get; set; }

        [Display(Name = "Arrival city")]
        public string ArrivalCity { get; set; }

        [Display(Name = "Planned transportations")]
        public int PlannedTransportations { get; set; }

        public int[] ActualPerDay { get; set; }

        [Display(Name = "Actual transportations")]
        public int ActualTransportations { get; set; }
    }
}

ReportsWebApp/Controllers/PlanActualReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReportsWebApp.Models;

namespace ReportsWebApp.Controllers
{
    [PlanReportAuthorizeFilter]
    public class PlanActualReportController : Controller
    {
        private ReportsWebAppDBEntities db = new ReportsWebAppDBEntities();

        // GET: 
        public ActionResult Index(string departureCity, string arrivalCity)
        {
            PlanReportModel model = new PlanReportModel();
            List<PlanActualReport> report = new List<PlanActualReport>();

            try
            {
                model.DepartureCities = db.Cities.Select(ct => ct.CityName).ToList();
                model.ArrivalCities = db.Cities.Select(ct => ct.CityName).ToList();
                var query = from plan in db.Plans
                            join ctFrom in db.Cities on plan.CityFromId equals ctFrom.Id
                            join ctTo in db.Cities on plan.CityToId equals ctTo.Id
                            join transp in db.Transportations on plan.Id equals transp.PlanId into transportations
                            select new PlanActualReport
                            {
                                PlanId = plan.Id,
                                DepartureCity = ctFrom.CityName,
                                ArrivalCity = ctTo.CityName,
                                PlannedTransportations = plan.PlannedTransportations,
                                ActualTransportations = transportations.Count()
                            };

                if (!string.IsNullOrEmpty(departureCity))
                {
                    query = from rep in query
                            where rep.DepartureCity == departureCity
                            select rep;
                }

                if (!string.IsNullOrEmpty(arrivalCity))
                {
                    query = from rep in query
                            where rep.ArrivalCity == arrivalCity
                            select rep;
                }

                report = query.ToList();

                foreach (var row in report)
                {
                    int[] days = new int[31];

                    for (int i = 0; i < 31; i++)
                    {
                        days[i] = 0;
                    }

                    var transportations = from trnsp in db.Transportations
                                          where trnsp.PlanId == row.PlanId
                                          select trnsp.DateTimeDeparture;
                    foreach (var trnsp in transportations)
                    {
                        days[trnsp.Day - 1]++;
                    }
                    row.ActualPerDay = days;
                }
            }
            catch (Exception ex)
            {
                Logger.Log.Error(ex);
            }
            ViewBag.Message = "Plan-actual report page.";
            model.report = report;

            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReportsWebApp/Views/PlanActualReport/Index.cshtml
@model ReportsWebApp.Models.PlanReportModel

@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("Index", "PlanActualReport", FormMethod.Get))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Filter</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.DepartureCities, "Departure city", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DepartureCity", new SelectList(Model.DepartureCities), "Select", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DepartureCities, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ArrivalCities, "Arrival city", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ArrivalCity", new SelectList(Model.ArrivalCities), "Select", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ArrivalCities, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Filter" class="btn btn-default" />
        </div>
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
}

<h1><strong>Plan-actual report</strong></h1>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.report.First().DepartureCity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.report.First().ArrivalCity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.report.First().PlannedTransportations)
        </th>

        @for (int i = 1; i <= 31; i++)
        {
            <th>
                @i
            </th>
        }
        <th>
            @Html.DisplayNameFor(model => model.report.First().ActualTransportations)
        </th>
    </tr>

    @foreach (var item in Model.report)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DepartureCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArrivalCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlannedTransportations)
            </td>

            @foreach (var day in item.ActualPerDay)
            {
                <td>
                    @Html.DisplayFor(modelItem => day)
                </td>
            }

            <td>
                @Html.DisplayFor(modelItem => item.ActualTransportations)
            </td>
        </tr>
    }

</table>